'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EmployeePage

    '''<summary>
    '''Txtnmfst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtnmfst As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Txtnmls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtnmls As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Txtbirth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtbirth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dropgen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropgen As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Txtcono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtcono As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Txtmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Txtads control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txtads As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dropposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropposition As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dropests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dropests As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Butemppg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Butemppg As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Butbank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Butbank As Global.System.Web.UI.WebControls.Button
End Class
